### ISSUE TITLE
funkwhale-beat  doesn't start

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/funkwhale_ynh#198]
### Describe the bug

funkwhale-beat doesn't start

### Context

- Hardware: VPS 
- YunoHost version: 
```
root@krashboyz:~# yunohost --version
yunohost: 
  repo: stable
  version: 11.1.10
yunohost-admin: 
  repo: stable
  version: 11.1.6
moulinette: 
  repo: stable
  version: 11.1.4
ssowat: 
  repo: stable
  version: 11.1.4
```
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch:
```
root@krashboyz:~# yunohost app info funkwhale 
description: Modern, convivial and free music server
domain_path: son.krashboyz.org/
name: Funkwhale
version: 1.2.9~ynh
```

### Steps to reproduce

- *If you performed a command from the CLI, the command itself is enough. For example:*
    ```sh
    sudo yunohost app install the_app
    ```
- *If you used the webadmin, please perform the equivalent command from the CLI first.*
yunohost/admin/#/services/funkwhale-beat  and restart the service

### Expected behavior

funkwhale-beat should running

### Logs

*When an operation fails, YunoHost provides a simple way to share the logs.*
- *In the webadmin*
https://paste.yunohost.org/ilezikakid
- *In command line*
```
root@krashboyz:~# yunohost service start funkwhale-beat
Success! Service 'funkwhale-beat' started

root@krashboyz:~# yunohost service status funkwhale-beat
configuration: unknown
description: funkwhale celery beat process
last_state_change: 2023-02-23 17:59:57
start_on_boot: enabled
status: failed
```
i found those closed tickets:
https://github.com/YunoHost-Apps/funkwhale_ynh/issues/111
https://github.com/YunoHost-Apps/funkwhale_ynh/issues/147
