### ISSUE TITLE
[funkwhale-beat] refuse to start correctly

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/funkwhale_ynh#286]
ynh on distant VPS
```
root@krashboyz:/var/log/funkwhale# yunohost --version
yunohost: 
  repo: stable
  version: 12.0.12
yunohost-admin: 
  repo: stable
  version: 12.0.7.1
yunohost-portal: 
  repo: stable
  version: 12.0.10
moulinette: 
  repo: stable
  version: 12.0.4
ssowat: 
  repo: stable
  version: 12.0.3
```
```
root@krashboyz:/var/log/funkwhale# yunohost app info funkwhale
description: Convivial and modern music server
domain_path: son.krashboyz.org/
name: Funkwhale
version: 1.4.0~ynh5
```

[python installed](https://krashboyz.org/zerobin/?0460a0945dd8725a#E26cZbJQ25qYU7khinSMEgh7Po8CSsiYgXxkjjECjArm)
 

Hello , 
as mentionned , funkwhale-beat is crashing:

last log in [`root@krashboyz:/var/log/funkwhale# cat funkwhale-beat.log`](https://krashboyz.org/zerobin/?b32efb5c97ff812d#BcyFgXiFSFK8GrNyvG5rHX7u6NXbUc33qwZ6cFm2ucm7)

thx for your help, 
i already tried to force upgrade as suggered in https://github.com/YunoHost-Apps/funkwhale_ynh/issues/282, 
but upgrade is broken https://github.com/YunoHost-Apps/funkwhale_ynh/issues/284
